spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false
    show-sql: false

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: info
