version: "3.8"

services:
  ticket-world-influxdb:
    image: bitnami/influxdb:1.8.5
    ports:
      - "8086:8086"
      - "8088:8088"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_DB=${INFLUXDB_DB}
    volumes:
      - ./ticket-world-influxdb-data:/var/lib/influxdb
    networks:
      - monitoring_net

  ticket-world-grafana:
    image: bitnami/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./ticket-world-grafana-data:/var/lib/grafana
    networks:
      - monitoring_net

  ticket-world-prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

volumes:
  ticket-world-influxdb-data:
  ticket-world-grafana-data:

networks:
  monitoring_net:
#    external: true
